/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Moje */

#ifndef _Included_Moje
#define _Included_Moje
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Moje
 * Method:    celecislo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Moje_celecislo
  (JNIEnv *, jclass, jint);

/*
 * Class:     Moje
 * Method:    pole
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Moje_pole
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
